In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення

In [4]:
arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення

In [5]:
zero = np.zeros((3, 3))

print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення

In [41]:
random = np.random.randint(1, 11, size=(5, 5))

print(random)

[[ 9  6  8  3  9]
 [ 6  1  2  1  7]
 [ 1  3  6  9  6]
 [ 9 10  8  1  8]
 [ 5  6  4  1 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

In [7]:
rand = np.random.rand(4, 4)

print(rand)

[[0.41334471 0.20796162 0.35806055 0.0080651 ]
 [0.99521969 0.74805649 0.07077504 0.73847212]
 [0.19070688 0.70791065 0.31867133 0.47571693]
 [0.24654502 0.16375267 0.65573981 0.36295878]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення

In [42]:
arr1 = np.random.randint(1, 11, size=5)
arr2 = np.random.randint(1, 11, size=5)

add_result = arr1 + arr2
sub_result = arr1 - arr2
mul_result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("arr1 + arr2:", add_result)
print("arr1 - arr2:", sub_result)
print("arr1 * arr2:", mul_result)

arr1: [2 8 6 5 1]
arr2: [1 9 9 1 3]
arr1 + arr2: [ 3 17 15  6  4]
arr1 - arr2: [ 1 -1 -3  4 -2]
arr1 * arr2: [ 2 72 54  5  3]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток

In [12]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([7, 6, 5, 4, 3, 2, 1])

dot = np.dot(a, b)

print(dot)

84


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою

In [43]:
A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 3))

C = np.dot(A, B)

print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Результат множення A і B:\n", C)

Матриця A:
 [[ 3 10]
 [ 9  8]]
Матриця B:
 [[ 8  6  8]
 [ 4 10  2]]
Результат множення A і B:
 [[ 64 118  44]
 [104 134  88]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю

In [44]:
A = np.random.randint(1, 11, size=(3, 3))

if np.linalg.det(A) != 0:
    A_inv = np.linalg.inv(A)
    print("Матриця A:\n", A)
    print("Обернена матриця A:\n", A_inv)
else:
    print("Матриця A є сингулярною, обернена матриця не існує.")

Матриця A:
 [[7 4 9]
 [9 1 3]
 [4 2 4]]
Обернена матриця A:
 [[-0.125   0.125   0.1875]
 [-1.5    -0.5     3.75  ]
 [ 0.875   0.125  -1.8125]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [30]:
A = np.random.rand(4, 4)

A_transposed = np.transpose(A)

print("Початкова матриця:\n", A)
print("Транспонована матриця:\n", A_transposed)

Початкова матриця:
 [[6.71622373e-01 6.51977508e-01 7.25972663e-01 5.44078607e-01]
 [4.10620122e-01 9.34159255e-01 2.78325668e-01 6.55701327e-01]
 [4.35565060e-01 6.20197389e-01 7.62755104e-03 8.12919780e-01]
 [8.83185763e-01 9.34239875e-02 7.16048691e-04 6.12579843e-01]]
Транспонована матриця:
 [[6.71622373e-01 4.10620122e-01 4.35565060e-01 8.83185763e-01]
 [6.51977508e-01 9.34159255e-01 6.20197389e-01 9.34239875e-02]
 [7.25972663e-01 2.78325668e-01 7.62755104e-03 7.16048691e-04]
 [5.44078607e-01 6.55701327e-01 8.12919780e-01 6.12579843e-01]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор

In [45]:
matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.randint(1, 11, size=4)

result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Результат:\n", result)

Матриця:
 [[10  8  9  4]
 [ 9  6  6  4]
 [ 1  6  8  5]]
Вектор:
 [10  8  3  8]
Результат:
 [223 188 122]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор

In [34]:
matrix = np.random.rand(2, 3)

vector = np.random.rand(3)

result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Результат:\n", result)

Матриця:
 [[0.84174858 0.17245821 0.49635907]
 [0.5494838  0.91362422 0.05471942]]
Вектор:
 [0.93393442 0.61888674 0.28746458]
Результат:
 [1.03555572 1.09434164]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення

In [46]:
A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

C = A * B

print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Результат поелементного множення:\n", C)

Матриця A:
 [[9 2]
 [5 3]]
Матриця B:
 [[10  1]
 [ 7  9]]
Результат поелементного множення:
 [[90  2]
 [35 27]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток

In [47]:
A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

C = np.dot(A, B)

print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Результат множення матриць A та B:\n", C)

Матриця A:
 [[8 9]
 [2 1]]
Матриця B:
 [[9 6]
 [1 3]]
Результат множення матриць A та B:
 [[81 75]
 [19 15]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці

In [48]:
matrix = np.random.randint(1, 101, size=(5, 5))

matrix_sum = np.sum(matrix)

print("Матриця:\n", matrix)
print("Сума елементів матриці: ", matrix_sum)

Матриця:
 [[ 91  24  54  86  26]
 [ 46  30  79  29  29]
 [  8  33  15  28  32]
 [100  86  25  35  69]
 [ 82  92  40  93   2]]
Сума елементів матриці:  1234


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю:

In [52]:
A = np.random.randint(1, 11, size=(4, 4))
B = np.random.randint(1, 11, size=(4, 4))

C = A - B

print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Різниця матриць A і B:\n", C)

Матриця A:
 [[ 8  2 10  9]
 [10  4  8  6]
 [ 2  3  2  6]
 [ 2  8  7  4]]
Матриця B:
 [[ 3  3 10  4]
 [ 9  4  7  7]
 [ 7  3  6  5]
 [ 8  5  9  9]]
Різниця матриць A і B:
 [[ 5 -1  0  5]
 [ 1  0  1 -1]
 [-5  0 -4  1]
 [-6  3 -2 -5]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці

In [53]:
matrix = np.random.rand(3, 3)
row_sums = matrix.sum(axis=1, keepdims=True)

print("Матриця:\n", matrix)
print("Вектор-стовпчик із сумами рядків:\n", row_sums)


Матриця:
 [[0.59230631 0.03088796 0.67678164]
 [0.97988219 0.58658444 0.51300629]
 [0.49906587 0.38025116 0.80552854]]
Вектор-стовпчик із сумами рядків:
 [[1.29997591]
 [2.07947293]
 [1.68484558]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел

In [54]:
matrix = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix)

print("Початкова матриця:\n", matrix)
print("Матриця з квадратами чисел:\n", squared_matrix)


Початкова матриця:
 [[1 7 9 1]
 [4 5 8 1]
 [9 9 3 5]]
Матриця з квадратами чисел:
 [[ 1 49 81  1]
 [16 25 64  1]
 [81 81  9 25]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел

In [56]:
vector = np.random.randint(1, 51, size=4)

sqrt_vector = np.sqrt(vector)

print("Вихідний вектор:\n", vector)
print("Вектор з квадратними коренями:\n", sqrt_vector)

Вихідний вектор:
 [48 16 45  9]
Вектор з квадратними коренями:
 [6.92820323 4.         6.70820393 3.        ]
